-- 부모(B)의 GENOTYPE이랑 자식(A)의 GENOTYPE이랑 & 연산을 했을 때
-- 부모의 GENOTYPE과 같으면 부모의 형질을 갖고 있는 것,

SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
FROM 
ECOLI_DATA A JOIN ECOLI_DATA B
ON A.PARENT_ID = B.ID 
WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY A.ID
